version: '2'
services:
  weather-scraper:
    container_name: weather-scraper
    build: ""
    networks:
      - home-network
    image: weatherscraper 
    env_file:
      - secrets/.env
    restart: always

  influxdb:
    container_name: influxdb
    image: docker.io/bitnami/influxdb:2
    ports:
      - 8086:8086
      - 8088:8088
    env_file:
      - secrets/.env
    volumes:
      - influxdb_data:/bitnami/influxdb
    restart: always
    networks:
      - home-network

volumes:
  influxdb_data:
    driver: local

networks:
  home-network:
    driver: bridge